### ISSUE TITLE
[Feature] Add MyPage_ (1) Follow Artist Section

### ISSUE THREAD

**Issue by seungsang00** [codestates/the-GOD-client#13]
### ISSUE
- Group:  `client`
- Type: `Add`
- Detail: 마이페이지 구현

### TODO
- [ ]  팔로우한 아티스트 리스트
    - [ ] 아티스트 언팔로우 기능 구현
    - [ ] 아티스트 클릭 시 아티스트 검색 결과 페이지로 라우팅
