### ISSUE TITLE
[Feature] Add search action

### ISSUE THREAD

**Issue by Reone1** [codestates/the-GOD-client#19]
### ISSUE
- Group:  `client`
- Type: `Add`
- Detail: API search action initialize

### TODO
1. [x] 검색 기능 구현
2. [x] 검색 결과 정상 확인
3. [ ] 검색 결과 없음 예외처리
