### ISSUE TITLE
[Feature] Add `sharedcontent` function

### ISSUE THREAD

**Issue by Reone1** [codestates/the-GOD-client#23]
### ISSUE
- Group:  `client`
- Type: `Add`
- Detail:  Add `sharedcontent` function

### TODO
1. [ ] 경로 생성 기능 실행 시 기능 전환 표시
2. [ ] 기능 구현
   1. [ ] 핀 클릭시
   2. [ ] 처음 선택된 컨텐츠 인경우 - 해당 컨텐츠는 리스트 최상단, 이미선택된 컨텐츠가 있다면 그 다음으로 들어간다.
   2. [ ] 이미 선택된 컨텐츠 인 경우 - 선택 해제 후, 원래 위치로 돌아간다.
   3. [ ] 공통 - 클릭 시마다 현재 리스트에 따라 경로를 그려준다.
   2. [ ] 리셋 클릭 시 - 선택된 모든 컨텐츠를 초기화 하고, 초기 검색 상태로 변경
   3. [ ] 공유 클릭 시 - 저장 요청 및 완료 시 링크 생성
   4. [ ] 저장 클릭 시 - 저장 요청
3. [ ] 테스트 코드
