### ISSUE TITLE
[Feature] Add ContentForm Page_(1) 기본정보 작성

### ISSUE THREAD

**Issue by seungsang00** [codestates/the-GOD-client#24]
### ISSUE
- Group:  `client`
- Type: `Add`
- Detail: 컨텐츠 작성 페이지 - Step 1. 기본정보 작성 구현

### TODO
- [ ]  대상 아티스트 select
- [ ]  이벤트 타이틀
- [ ]  사진, 동영상 파일 업로드
    - [ ] 업로드 시 미리보기 썸네일 기능 구현 
- [ ]  이벤트 설명글
- [ ]  태그 추가 기능
    - [ ] 태그 추가 기능 - 중복 검사
    - [ ] 태그 삭제 기능 - 클릭 이벤트
- [ ] 모든 필수항목이 입력되면 사이드 바에 완료 표시 (또는 다음단계 버튼 활성화)
