### ISSUE TITLE
[Feature] Add Responsible Layout Design

### ISSUE THREAD

**Issue by Reone1** [codestates/the-GOD-client#6]
### ISSUE
- Group:  `client`
- Type: `docs`, `add`
- Detail: 반응형 레이이아웃 설정

### TODO
1. [x] 컬럼 기준 정하기
2. [x] 반응형 지원 디바이스 선정
3. [x] 페이지별 레이아웃 결정
4. [x] 페이지별 반응형 레이아웃 조정
