### ISSUE TITLE
[Feature] Add Atomic components Initialize

### ISSUE THREAD

**Issue by Reone1** [codestates/the-GOD-client#8]
### ISSUE
- Group:  `client`
- Type: `Add`, 
- Detail: Atomic components Initialize

### TODO
1. [x] 최소단위 컴포넌트 리스트업
2. [x] 리스트에 따른 컴포넌트 작업 분배
3. [x] 컴포넌트 구현 및 기초 디자인 적용
4. [x] 테마
5. [x] 글로벌 스타일
